[tools]
"asdf:neovim" = "nightly"
atuin = "18.10.0"
difftastic = "0.67.0"
docker-cli = "29.0.0"
jj = "0.35.0"
jjui = "0.9.6"
tree-sitter = "0.25.10"
zellij = "0.43.1"
bun = "1.3.2"
go = "1.25.4"
node = "25.2.0"
poetry = "2.2.1"
usage = "2.8.0"
dust = "1.2.3"
eza = "0.23.4"
