[tools]
atuin = "18.11.0"
difftastic = "0.67.0"
docker-cli = "29.2.1"
jj = "0.38.0"
jjui = "0.9.10"
tree-sitter = "0.26.5"
zellij = "0.43.1"
bun = "1.3.8"
go = "1.25.7"
node = "25.6.0"
poetry = "2.3.2"
usage = "2.16.1"
dust = "1.2.4"
eza = "0.23.4"
lazydocker = "0.24.4"
python = "3.14.3"
zig = "master"
opencode = "1.1.53"
fzf = "0.67.0"
zoxide = "0.9.9"
lazygit = "0.58.1"
fd = "10.3.0"
xh = "0.25.3"
"cargo:somo" = "latest"
"cargo:bacon" = "latest"
ripgrep = "15.1.0"
jq = "1.8.1"
zls = "0.15.1"
stylua = "2.3.1"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"github:pythops/impala" = "latest"
"github:pythops/bluetui" = "latest"
"asdf:neovim" = "0.11.6"
pitchfork = "1.3.0"

[settings]
experimental = true

[settings.npm]
package_manager = "bun"
