[tools]
"asdf:neovim" = "nightly"
atuin = "18.10.0"
difftastic = "0.67.0"
docker-cli = "29.1.2"
jj = "0.36.0"
jjui = "0.9.7"
tree-sitter = "0.26.1"
zellij = "0.43.1"
bun = "1.3.4"
go = "1.25.5"
node = "25.2.1"
poetry = "2.2.1"
usage = "2.9.0"
dust = "1.2.3"
eza = "0.23.4"
