[tools]
"asdf:neovim" = "0"
atuin = "18.11.0"
difftastic = "0.67.0"
docker-cli = "29.1.5"
jj = "0.37.0"
jjui = "0.9.10"
tree-sitter = "0.26.3"
zellij = "0.43.1"
bun = "1.3.6"
go = "1.25.6"
node = "25.4.0"
poetry = "2.3.1"
usage = "2.13.1"
dust = "1.2.4"
eza = "0.23.4"
lazydocker = "0.24.4"
python = "3.14.2"
zig = "0.15.2"
opencode = "1.1.28"
fzf = "0.67.0"
zoxide = "0.9.8"
lazygit = "0.58.1"
fd = "10.3.0"
