# theme = "onedark"
theme = "gruvbox-material"
# theme = "ashen"

# ====================================================================================================

[editor]
scrolloff = 28
continue-comments = false
bufferline = "multiple"
trim-final-newlines = true
trim-trailing-whitespace = true
clipboard-provider = "x-clip"
line-number = "relative"
color-modes = true
completion-trigger-len = 1
true-color = true
mouse = false

soft-wrap.enable = true
cursor-shape.insert = "bar"
file-picker.hidden = false

# ====================================================================================================

[editor.lsp]
display-progress-messages = true
# display-inlay-hints = true

# ====================================================================================================

# ====================================================================================================
# TODO
# a.in selection mode (visual) go to word with gw/s while maintaining the selection
# b.in selection mode move the selected content with alt + h,j,k,l
# c.add old files picker
# d.when closing and opening files the cursor should remember the previous position the same goes with copying the entire file
# ====================================================================================================

# ====================================================================================================

[keys.select]
"A-e" = "match_brackets"
"S-h" = "goto_line_start"
"S-l" = "goto_line_end"
"f" = ["normal_mode", "collapse_selection"]
"S" = "select_regex"
"space" = { ";" = "toggle_comments" }

[keys.normal]
"A-v" = ["goto_line_end", "select_mode", "goto_line_start"]
"A-e" = "match_brackets"
"C-c" = "@%y"
"S-h" = ["insert_at_line_start", "normal_mode"]
"S-l" = "goto_line_end"
"tab" = ":buffer-next"
"f" = "collapse_selection"
"D" = ["select_mode", "goto_line_end", "delete_selection"]
"s" = "goto_word"
"S-tab" = ":buffer-previous"
";" = { "e" = ":write-quit-all", "w" = ":write-all", "s" = "search", "n" = ":quit-all!" }

[keys.normal.space]
";" = "toggle_comments"
"o" = ":config-reload"
# "a" = "file_explorer"
# "e" = "file_picker"

# "F" = "no_op"
"r" = "no_op"
"'" = "no_op"
# "Y" = "no_op"
"P" = "no_op"
"d" = "no_op"
"D" = "no_op"
"C" = "no_op"
# "S" = "no_op"
# "j" = "no_op"
"/" = "no_op"
"?" = "no_op"
"A-c" = "no_op"

[keys.normal.space.c]
"a" = "code_action"
"r" = "rename_symbol"

[keys.normal.space.s]
"k" = "command_palette"
"g" = "global_search"
"d" = "diagnostics_picker"
"D" = "workspace_diagnostics_picker"

[keys.normal.space.f]
"b" = "buffer_picker"

[keys.normal.space.b]
"d" = ":buffer-close"
"o" = ":buffer-close-others"

[keys.insert]
"A-h" = "move_char_left"
"A-l" = "move_char_right"
"A-j" = "move_line_down"
"A-k" = "move_line_up"

"j" = { "k" = "normal_mode" }
