# theme = "onedark"
theme = "gruvbox-material"
# theme = "ashen"
# ====================================================================================================

[editor]
scrolloff = 28
continue-comments = false
bufferline = "multiple"
trim-final-newlines = true
trim-trailing-whitespace = true
clipboard-provider = "wayland"
line-number = "relative"
color-modes = true
auto-pairs = true
auto-format = true
completion-trigger-len = 1
true-color = true
mouse = false

# ====================================================================================================

[editor.auto-save]
after-delay.enable = false
after-delay.timeout = 500

# ====================================================================================================

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = []
right = [
  "version-control",
  "spacer",
  "diagnostics",
  "total-line-numbers",
  "position",
  "file-encoding",
  "file-type",
]
separator = "â”‚"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

# ====================================================================================================

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

# ====================================================================================================

[editor.file-picker]
hidden = false

# ====================================================================================================

[keys.select]
"A-e" = "match_brackets"
"S-h" = "goto_line_start"
"S-l" = "goto_line_end"
"f" = ["normal_mode", "collapse_selection"]
";" = "toggle_comments"
"g" = { "a" = "goto_last_line", "e" = "no_op" }

"s" = "goto_word"
"S" = "select_regex"

[keys.normal]
"A-v" = ["goto_line_start","select_mode","goto_line_end"]
"A-e" = "match_brackets"
"C-c" = "@%y"
"S-h" = ["insert_at_line_start", "normal_mode"]
"S-l" = "goto_line_end"
"tab" = ":buffer-next"
"f" = "collapse_selection"
"D" = ["select_mode","goto_line_end","delete_selection"]
"s" = "goto_word"
"S" = "select_regex"
"S-tab" = ":buffer-previous"
"g" = { "a" = "goto_last_line", "e" = "no_op" }
";" = { "e" = ":write-quit-all", "w" = ":write-all", "s" = "search", "n" = ":quit-all!" }

[keys.normal.space]
";" = "toggle_comments"
"o" = ":config-reload"
"a" = "file_explorer"
"e" = "file_picker"

"F" = "no_op"
# "a" = "no_op"
"r" = "no_op"
"'" = "no_op"
"E" = "no_op"
# "y" = "no_op"
"Y" = "no_op"
"P" = "no_op"
"d" = "no_op"
"D" = "no_op"
"C" = "no_op"
# "g" = "no_op"
"S" = "no_op"
"j" = "no_op"
"/" = "no_op"
"?" = "no_op"
"A-c" = "no_op"

[keys.normal.space.c]
"a" = "code_action"
"r" = "rename_symbol"

[keys.normal.space.s]
"k" = "command_palette"
"g" = "global_search"
"b" = "search"
"d" = "diagnostics_picker"
"D" = "workspace_diagnostics_picker"

[keys.normal.space.f]
"b" = "buffer_picker"

[keys.normal.space.b]
"d" = ":buffer-close"
"o" = ":buffer-close-others"

[keys.insert]
"A-h" = "move_char_left"
"A-l" = "move_char_right"
"A-j" = "move_line_down"
"A-k" = "move_line_up"

"j" = { "k" = "normal_mode" }
