
[language-server.oxlint-language-server]
command = "oxlint"
args = ["--lsp"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "oxlint-language-server"]
formatter = { command = "oxfmt", args = ["--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "oxlint-language-server"]
formatter = { command = "oxfmt", args = ["--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "oxlint-language-server"]
formatter = { command = "oxfmt", args = ["--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "oxlint-language-server"]
formatter = { command = "oxfmt", args = ["--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "oxfmt", args = ["--stdin-filepath", "%{buffer_name}"] }
auto-format = true


[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
